# Generated by Django 5.2 on 2025-08-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du fruit')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description du fruit')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/fruits', verbose_name='Image du fruit')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
